### ISSUE TITLE
Error on compile: gcc.exe: error: unrecognized command line option '-rdynamic'

### ISSUE THREAD

**Issue by ShadowElf37** [mantielero/VapourSynth.nim#1]
I have a single Nim file that just does `import vapoursynth`, and it keeps complaining that there's not command line option '-rdynamic'. Windows 10, Nim 1.4.2.

```
C:\...\video.nim(1, 8) Warning: imported and not used: 'vapoursynth' [UnusedImport]
Hint:  [Link]
gcc.exe: error: unrecognized command line option '-rdynamic'
Error: execution of an external program failed: 'gcc.exe   -o ...  -rdynamic -Wl,-wrap,dlopen   '
```

I've been poking at it for a few hours, and all I know is it's happening to the linker. I've tried passing `-Wno-unknown-warning`, but that doesn't help either. As far as I can tell this is a bug, or my installation is wrong.

**Comment by mantielero** [comment]
I never tested it on windows. I will take a look.

**Comment by mantielero** [comment]
Could you check if now it works for you?

**Comment by ShadowElf37** [comment]
Compiles perfectly, thank you so much.
